config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#landing'


  resources :users do
    resources :events, only: [:new, :create, :edit]
    resources :posts, only: [:new, :create, :edit]
  end
  resources :events, except: [:new, :create, :edit]
  resources :posts, except: [:new, :create, :edit]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :manage, :dashboard
    end

    if user.supervisor_role?
      can :manage, Post, user_id: user.id
      can :manage, Event, user_id: user.id
    end
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :date, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def summarize
    "#{title} - #{location} - #{date}"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true

  def summarize
    "#{title} - #{created_at} - #{user.username}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :posts
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :only => [:show]

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :update, :destroy, :summarize]

  def index
    @events = Event.all
  end

  def new
    @user = current_user
    # if current_user.superadmin_role? || current_user.supervisor_role?
      @event = Event.new
    # else
      # redirect_to root_path
    # end
     # needed to instantiate the form_for
  end

  def create

   @event = Event.new(event_params)
   @user = current_user
   @event.user = @user
    if @event.save!
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update

    @event.update(event_params)
    @event.save # needed to instantiate the form_for
    redirect_to event_path
  end

  def edit

  end

  def show
  end

  def destroy

    @user = current_user
    @event.destroy

    # no need for app/views/users/destroy.html.erb
    redirect_to user_path(@user)
  end

  def add_tag
    # set_event
    # puts @event
    # @tags = []
    # # @tags << userinput

  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :location, :description, :seats, :picture, :speakers, :date, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @user = current_user
    @post = Post.new # needed to instantiate the form_for
  end

  def create
   @post = Post.new(post_params)
   @user = current_user
   @post.user = @user
    if @post.save!
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update
    @post.update(post_params)
    @post.save # needed to instantiate the form_for
    redirect_to post_path
  end

  def edit
  end

  def show
  end

  def destroy
    @user = current_user
    @post.destroy

    # no need for app/views/users/destroy.html.erb
    redirect_to user_path(@user)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end


  def post_params
    params.require(:post).permit(:title, :location, :description, :seats, :picture, :speakers, :date, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name,:email, :picture, :description, :username)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<div class="container">
  <ul>
    <% @events.each do |event| %>
      <li><%= event.title %> - <%= event.date %> - <%= event.location %></li>
    <% end %>
  </ul>

</div>

app/views/events/new.html.erb
<h1 class="text-center text-danger">Create new event</h1>


<div class="form-container">
  <%= simple_form_for [ @user, @event ] do |f| %>
  <%= f.error_notification %>

<div class="form-group">
  <%= f.input :title %>
</div>


  <%= f.input :description, type: "textarea" %>

  <%= f.input :picture, as: :file %>

  <%= f.input :seats %>

  <%= f.input :location %>

  <%= f.input :date %>

  <%= f.button :submit, class: "btn-primary" %>
   <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
  <% end %>


</div>

app/views/events/show.html.erb
<div class="container">
  <div class="event_card">
    <div class="event_info">
      <div class="title"><%= @event.title %></div>
      <div class="specs">
        <div class="specs1">
          <div class="specs"><%= @event.location %></div>
          <div class="specs"><%= @event.date %></div>
        </div>
        <div class="spec2">
          <div class="specs"><%= @event.speakers %></div>
          <div class="specs"><%= @event.seats %></div>
        </div>
      </div>
    </div>
    <div class="event_description">
      <%= @event.description  %>
    </div>
  </div>

  <div class="event_action">
    <ul>
      <li data-toggle="modal" data-target="#editModal">Edit event</li>
      <li class=""><%= link_to "Delete #{@event.title}",
            event_path(@event),
            method: :delete,
            data: { confirm: "Are you sure?" }
          %>
        </li>
        <li><%= link_to "Back to the Dashboard", user_path(current_user) %></li>
    </ul>
  </div>
</div>



<!-- MODALS -->

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit your profile info!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <%= simple_form_for [@event] do |f| %>
         <%= f.input :title, label: 'Username', :input_html => { :value => @event.title } %>
         <%= f.input :date %>
         <%= f.input :location %>
         <%= f.input :seats %>
         <%= f.input :speakers %>
         <%= f.input :picture, label: 'Profile picture' %>
         <%= f.input :description, label: 'Description' %>
         <%= f.submit "validate", class: "btn btn-primary" %>
       <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KodoGeocoded</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<link href="//db.onlinewebfonts.com/c/1e20e698946e398f2ad70318ce64c215?family=Salome" rel="stylesheet" type="text/css"/>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>



    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= javascript_pack_tag "application" %>

     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="text-center">HELLO KODO</h1>

<div class="latest_events">
  <h3>LATEST EVENTS : </h3>
  <% e = Event.last(3) %>
  <% e.each do |event| %>
    <h6><%= event.summarize %></h6>
  <% end %>
</div>

<div class="latest_events">
  <h3>LATEST POSTS : </h3>
  <% posts = Post.last(3) %>
  <% posts.each do |post| %>
    <h6><%= post.summarize %></h6>
  <% end %>
</div>

<h1>HEYYYYY links</h1>


<% if can? :read, @posts %>
  <%= link_to "View", posts_path %>
<% end %>

<% if current_user %>
  <% if current_user.superadmin_role? || current_user.supervisor_role? %>
    <p>Visible only for superadmins and supervisors! </p>
  <% end %>
<% end %>

app/views/pages/landing.html.erb
<div class="bg">
  <div class="container_wide">
    <div class="top_bar">
      <a href="mailto:hello@kodotalk.com" class="mail desktop">hello@kodotalk.com</a>
      <div class="wip">
        <p class="woop flex-vertical">SERVICE EN CONSTRUCTION</p>
        <div class="wip_content no_show">
          <p>Hop hop hop! Pas si vite! La plateforme Kôdô est en construction pour rendre les savoirs accessibles à tous, partout et tout le temps.<br><br>Pour la suite de l’aventure, rejoignez la communauté grâce à notre <a href="">newsletter</a> et nos <a href="">Réseaux sociaux</a>!</p>
          <button class="blue_btn">Compris ! Je m'inscris</button>
        </div>
      </div>
    </div>
    <div class="main_stuff">
      <div class="img_info">
        <div class="images">
            <div class="logo"><%= image_tag("Logo_KODO.png", class:"kodo_logo")  %></div>
          </div>
        <div class="info">
          <h1 class="know_again">Reprenons connaissance !</h1>
          <h5 class="xp">L'expérience des conférences au delà des bancs de l'amphi</h5>
        </div>
      </div>

      <div class="low_bar desktop">
        <div class="newsletter">
          <div class="box_title">
            <p class="title">Newsletter</p>
            <div class="icons"> <%= image_tag("NL.png") %></div>
          </div>

          <div class="nl_content no_show">
            <p class="subtitle">Restons connectés</p>
            <p class="text">Tous les mois, recevez des news et des contenus éclairés tout droit sortis de l’observatoire Kôdô !</p>
          </div>
        </div>
         <div class="know_more">
          <div class="box_title">
            <p class="title">En savoir plus</p>
            <div class="icons"> <%= image_tag("Play.png") %></div>
          </div>

          <div class="km_content no_show">
            <p class="text" style="text-align: justify;">Nous sommes le pont entre vous et l’infini savoir.<br><br>

Nous voulons mettre en lumière les chercheurs, leur travail et leurs découvertes.<br><br>

Nous avons la conviction qu’ensemble nous pouvons créer un espace inédit. Un espace où les savoirs priment sur l’opinion.</p>
          </div>
        </div>
         <div class="follow">
          <div class="box_title">
            <p class="title">Suivez-nous</p>
            <div class="icons"> <%= image_tag("Consulter.png") %></div>
          </div>

          <div class="fllw_content no_show">
            <div class="insta" style="height: 50%; background-color: blue" >Instagram</div>
            <div class="fb" style="height: 50%; background-color: white" >Facebook</div>
          </div>
        </div>
      </div>

      <div class="nl_contentm no_show">
        <p class="subtitle">Restons connectés</p>
        <p class="text">Tous les mois, recevez des news et des contenus éclairés tout droit sortis de l’observatoire Kôdô !</p>
      </div>

       <div class="km_contentm no_show">
            <p class="text" style="text-align: justify;">Nous sommes le pont entre vous et l’infini savoir.<br><br>

Nous voulons mettre en lumière les chercheurs, leur travail et leurs découvertes.<br><br>

Nous avons la conviction qu’ensemble nous pouvons créer un espace inédit. Un espace où les savoirs priment sur l’opinion.</p>
      </div>

      <div class="fllw_contentm no_show">
        <div class="insta" style="height: 50%; background-color: blue" >Instagram</div>
        <div class="fb" style="height: 50%; background-color: white" >Facebook</div>
      </div>

            <div class="low_bar mobile">
              <div class="newsletterm">
                <div class="box_title">
                  <p class="title">Newsletter</p>
                  <div class="icons"> <%= image_tag("NL.png") %></div>
                </div>

              </div>
               <div class="know_morem">
                <div class="box_title">
                  <p class="title">En savoir plus</p>
                  <div class="icons"> <%= image_tag("Play.png") %></div>
                </div>

              </div>
               <div class="followm">
                <div class="box_title">
                  <p class="title">Suivez-nous</p>
                  <div class="icons"> <%= image_tag("Consulter.png") %></div>
                </div>


              </div>
            </div>




    </div>

  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <ul>
    <% @posts.each do |post| %>
      <li><%= post.title %> - <%= post.created_at %> - <%= post.user.username %></li>
    <% end %>
  </ul>

</div>

app/views/posts/new.html.erb
<h1 class="text-center text-danger">Create new post</h1>


<div class="form-container">
  <%= simple_form_for [ @user, @post ] do |f| %>
  <%= f.error_notification %>

<div class="form-group">
  <%= f.input :title %>
</div>

  <%= f.input :description, type: "textarea" %>

  <%= f.input :picture, as: :file %>

  <%= f.button :submit, class: "btn-primary" %>
   <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
  <% end %>


</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="post_card">
    <div class=""><%= @post.title %></div>
    <div class=""><%= @post.description %></div>
    <div class=""><div><%= @post.created_at %></div><div><%= @post.user.username %></div></div>
  </div>



  <div class="event_action">
    <ul>
      <li data-toggle="modal" data-target="#editModal">Edit post</li>
      <li class=""><%= link_to "Delete #{@post.title}",
            post_path(@post),
            method: :delete,
            data: { confirm: "Are you sure?" }
          %>
        </li>
      <li><%= link_to "Back to the Dashboard", user_path(current_user) %></li>
    </ul>
  </div>
</div>




</div>

<!-- MODALS -->

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit this post :</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <%= simple_form_for [@post] do |f| %>
         <%= f.input :title, label: 'Username', :input_html => { :value => @post.title } %>
         <%= f.input :picture, label: 'Profile picture' %>
         <%= f.input :description, label: 'Description' %>
         <%= f.submit "validate", class: "btn btn-primary" %>
       <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("https://res.cloudinary.com/dpwhjxnci/image/upload/w_1000,ar_16:9,c_fill,g_auto,e_sharpen/v1583344633/KODO/SYSTEM/KODO_Logo_Box_Transparent_Blue_hb2ikh.png", width: 80, crop: :fill) %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Events", events_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Posts", posts_path, class: "nav-link" %>
        </li>

      <% if user_signed_in? %>


        <li class="nav-item">
          <%= link_to "Dashboard", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Create Event", new_user_event_path(current_user.id), class: "dropdown-item" %>
            <%= link_to "Create Post", new_user_post_path(current_user.id), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>DASHBOARD</h1>

<div class="">
  <h1>hello <%= @user.username %></h1>
  <h3><%= @user.email %></h3>
  <h4><%= @user.description %></h4>

  <div class="user_actions">
    <div class="edit-part"><h4><i data-toggle="modal" data-target="#editModal" class="fas fa-user-edit"></i></h4></div>
  </div>
  </div>


  <div class="actions">
    <ul>
      <li><%= link_to "New event", new_user_event_path(@user.id) %></li>
      <li><%= link_to "New post",  new_user_post_path(@user.id) %></li>
    </ul>

  </div>


  <div class="user_events">
    <h2>My events</h2>
    <ul>
       <% @user.events.each do |event|%>
        <li><%= link_to "#{event.title} - #{event.date} - #{event.location}", event_path(event) %></li>
      <% end %>
    </ul>
  </div>

  <div class="user_posts">
    <h2>My posts</h2>
    <ul>
       <% @user.posts.each do |post|%>
        <li><%= link_to "#{post.title} - #{post.created_at} - #{post.user.username}", post_path(post) %></li>
      <% end %>
    </ul>
  </div>

  <!-- MODALS -->

  <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit your profile info!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
         <%= simple_form_for [@user] do |f| %>
           <%= f.input :username, label: 'Username', :input_html => { :value => current_user.username } %>
           <%= f.input :email %>
           <%= f.input :picture, label: 'Profile picture' %>
           <%= f.input :description, label: 'Description' %>
           <%= f.submit "validate", class: "btn btn-primary" %>
         <% end %>
        </div>
      </div>
    </div>
  </div>



</div>